const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
    title: 'Express API Documentation',
    description: 'Automatically generated by swagger-autogen'
  },
  host: 'localhost:3000',  
  schemes: ['http']    
};

const outputFile = './swagger-output.json';
const endpointsFiles = ['./app.js'];        

swaggerAutogen(outputFile, endpointsFiles, doc);